# GitHub Pages'ga Vite loyihasini deploy qilish uchun to'g'ri workflow
name: Deploy Vite app to Pages

on:
  # 'main' branch'ga 'push' bo'lganda ishga tushadi
  push:
    branches: ["main"]
  
  # Actions tab'idan qo'lda ishga tushirishga ruxsat beradi
  workflow_dispatch:

# GITHUB_TOKEN'ga deploy qilish uchun ruxsat berish
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # --- QO'SHILGAN QADAMLAR BOSHLANISHI ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Yoki siz ishlatayotgan mos Node.js versiyasi
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci # 'npm install'dan tezroq va xavfsizroq
        
      - name: Build
        run: npm run build # Loyihani 'dist' papkasiga build qiladi
      # --- QO'SHILGAN QADAMLAR TUGADI ---

      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # '.' o'rniga 'dist' papkasini yuklaymiz
          path: 'dist' 
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
